export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  TOURNAMENT_NAME_REQUIRED: 'TOURNAMENT_NAME_REQUIRED',
  INVALID_PARTICIPANT_COUNT: 'INVALID_PARTICIPANT_COUNT',
  INVALID_MIXED_GENDER_DISTRIBUTION: 'INVALID_MIXED_GENDER_DISTRIBUTION',
  INVALID_SCORE: 'INVALID_SCORE',
  MATCHES_ALREADY_GENERATED: 'MATCHES_ALREADY_GENERATED',
  TOURNAMENT_ALREADY_STARTED: 'TOURNAMENT_ALREADY_STARTED',
  TOURNAMENT_ALREADY_FINISHED: 'TOURNAMENT_ALREADY_FINISHED',
  MATCH_ALREADY_FINISHED: 'MATCH_ALREADY_FINISHED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  TOURNAMENT_NOT_FOUND: 'TOURNAMENT_NOT_FOUND',
  PARTICIPANT_NOT_FOUND: 'PARTICIPANT_NOT_FOUND',
  MATCH_NOT_FOUND: 'MATCH_NOT_FOUND',
  PUBLIC_LINK_EXPIRED: 'PUBLIC_LINK_EXPIRED',
  PUBLIC_LINK_REVOKED: 'PUBLIC_LINK_REVOKED',
  PUBLIC_LINK_INVALID: 'PUBLIC_LINK_INVALID',
  BUSINESS_RULE_ERROR: 'BUSINESS_RULE_ERROR',
  INTEGRATION_ERROR: 'INTEGRATION_ERROR',
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
